# Generated by Django 3.0.5 on 2020-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=128)),
                ('blog_desc', models.CharField(max_length=2048)),
                ('blog_img', models.ImageField(upload_to='imgs/')),
            ],
        ),
    ]
