# Generated by Django 3.0.5 on 2020-04-25 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=128)),
                ('job_img', models.ImageField(upload_to='imgs/')),
                ('job_summary', models.CharField(max_length=512)),
            ],
        ),
    ]
